### ISSUE TITLE
syshud can only display one hud per runtime?

### ISSUE THREAD

**Issue by littleblack111** [System64fumo/syshud#14] opened 2024-09-11 14:14 UTC
atm. if i have brightness on -M or monitor. it will only show hud on brightness. without brightness, it will only show hud on audio.
had to launch syshud -M audio_in,audio_out and  syshud -M brightness at the same time?

**Comment by System64fumo** [comment] 2024-09-11 14:30
I'm failing to understand your question.
Do you mean you want to see both bars at the same time?
Something like this?
![img](https://github.com/user-attachments/assets/a66e70d5-fb54-41e7-95aa-834e8fa20091)

**Comment by littleblack111** [comment] 2024-09-11 14:45
ooo. i see whats going on here... it will work for both audio and brightness if i add -b /sys/bus/ddcci/devices/ddcci13/backlight/ddcci13. but would only have brightness if its not set. which the brightness still displayed properly...

**Comment by System64fumo** [comment] 2024-09-11 14:48
What do you mean by that?
If you don't have a backlight set it should automatically detect the first backlight available in `/sys/class/backlight/` when the brightness monitor is enabled.
-b is for custom paths in case you don't want to use the first available backlight (Or in my case using a fake backlight)

**Comment by littleblack111** [comment] 2024-09-11 14:52
im confused too... -b /sys/class/backlight doesnt work. but /sys/class/backlight/ddcci13. probroblly cuz im using dccii driver for external monitor to work? but the automatic one work without -b. but the audio doesnt with the automaticly set -b

**Comment by System64fumo** [comment] 2024-09-11 14:57
No you just don't understand how this works.

The automatic detection path is: `/sys/class/backlight/`
It will search for the first instance of a backlight which in your case is `ddcci13`
Then will monitor  `/sys/class/backlight/ddcci13/brightness`

Using a custom path selects the backlight directly
So instead of searching for a directory in that path it will assume that the path you gave it is the path containing `brightness` and `max_brightness` files

**Comment by System64fumo** [comment] 2024-09-11 15:03
Hummmmm interesting behavior..
What version of syshud are you on just to double check?

**Comment by System64fumo** [comment] 2024-09-11 15:07
Wait.. Oh my god.. i figured it out..
Do you have a config in ~/.config/sys64/hud/config.conf?
Because you're supposed to configure syshud with that otherwise the defaults will load from /usr/share/sys64/hud/config.conf...

**Comment by System64fumo** [comment] 2024-09-11 15:10
Yeah.. consider copying /usr/share/sys64/hud/config.conf to ~/.config/sys64/hud/config.conf then make your changes there
Things should work alright after that.. *Hopefully*

**Comment by System64fumo** [comment] 2024-09-23 11:36
Out of curiosity @littleblack111 have things improved recently?
I feel like https://github.com/System64fumo/syshud/commit/d667cdfffda6e627216f2814a65041a7391c1b68 could have helped this?

**Comment by littleblack111** [comment] 2024-09-23 11:38
the warning or sth did go away. but its still doing that...

**Comment by System64fumo** [comment] 2024-09-23 11:43
Dang.. I really don't know then..
Works fine on my phone though so i know the brightness indicator works alongside audio.
Same for desktop (With a virtual backlight)

I guess this issue is related to the ddc driver, Can you check on another system of yours with a backlight (If you have one)
Or create the following:
`/tmp/backlight/brightness` (echo 0 to it)
`/tmp/backlight/max_brightness` (echo 100 to it)
Then
`syshud -M "audio_out,brightness" -b "/tmp/backlight"`

**Comment by littleblack111** [comment] 2024-09-23 11:46
idk...

╰─$ syshud -M "audio_out,brightness" -b "/tmp/backlight"                                                ─╯
Key 'keyboard' not found in section 'main'
Backlight: /tmp/backlight
Output: alsa_output.pci-0000_00_1f.3.analog-stereo, ID: 58
Input: alsa_input.usb-046d_Logitech_BRIO_403C18BA-03.analog-stereo, ID: 57

again, -M will work. but automatic/from config doesnt work

**Comment by System64fumo** [comment] 2024-09-23 11:48
So the virtual /tmp/backlight works but automatic (ddc) does not?

**Comment by littleblack111** [comment] 2024-09-23 11:50
> So the virtual /tmp/backlight works but automatic (ddc) does not?

automaticly set ddc will remove audio. but if i unload the driver, it will only have audio...

current solution: specifying via -M to ddc and audio

**Comment by System64fumo** [comment] 2024-09-23 11:53
I'm still sort of confused by what you mean but i will assume that there's a fault in the ddc driver, I would like to test it myself however i can't seem to build it on my system.
Can't reproduce the issue you're having either so not much i can do myself.

I will be closing this issue though feel free to re-open if you have a better idea on what's failing.

**Comment by littleblack111** [comment] 2024-09-23 11:55
please dont close it as completed, as its not completed, close it as not planned as its not being able to repoduce...

also ddcc driver have issue with the latest and greatest kernel. a PR is awaiting merge: https://gitlab.com/ddcci-driver-linux/ddcci-driver-linux/-/merge_requests/16

**Comment by System64fumo** [comment] 2024-09-26 16:24
@littleblack111 I've got both good news and bad news.

Good news: I was able to reproduce and fix this.
Bad news: I don't know how the issue happens.

If [this](https://github.com/System64fumo/syshud/blob/7999cd8e6ac0d18487a1d3ec49cb5b56e2b0e03c/src/backlight.cpp#L21) return ever runs wireplumber stops working, Switching it with a continue fixes audio monitoring.
I would like to figure out why this is the case first before pushing but if you want you can just change the return with a continue.

**Closed** 2024-09-26 21:18 UTC

**Comment by littleblack111** [comment] 2024-09-27 08:03
I see. Thank you for the fix!
